management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
my:
  app:
    language: eng
    props:
      addresses:
        - city: istanbul
          street: atasehir
        - city: ankara
          street: mamak
        - city: izmir
          street: karşıyaka
      application: app1
      description: deneme training
      eir-props:
        bind-address: istanbul xyz
        port: 7088
        prefix: pref1
      git-version: 1.1.0
      locations:
        - istanbul
        - ankara
        - izmir
      phone-map:
        ev:
          name: en numarası
          number: 327646342
        ofis:
          name: ofis numarası
          number: 237462364
      rule: rule1
      socket-port: 10000
      test-version: 5
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: 9090
spring:
  application:
    name: spring-training-20241216
  profiles:
    default: live
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./data/demo
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
app:
  group:
    name: test